#!/usr/bin/env bash
# configures a new Ubuntu machine
# Install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using
# curl, it must return a page that contains the string Holberton School
echo "Holberton School" | tee /var/www/html/index.html
sed -i '/listen port 80 default_server; /a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n}\n' /etc/nginx/sites-available/default
sudo service nginx start
