#!/usr/bin/env bash
# configures a new Ubuntu machine
# Install nginx web server
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using
# curl, it must return a page that contains the string Holberton School
echo "Ceci n'est pas une page" | sudo tee usr/share/nginx/html/404.html
newlines="\\\final_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot usr/share/nginx/html/;\n\t\tinternal;\n\t}"
sudo sed -i "27i $newlines"  /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
