#!/usr/bin/env bash
# configures a new Ubuntu machine
# shellcheck disable=SC2154
#  configures a brand new Ubuntu machine
sudo apt-get -y update
sudo apt-get -y install nginx
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using
# curl, it must return a page that contains the string Holberton School
sed -i "/http {/a add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx start
