#!/usr/bin/env bash
# configures a new Ubuntu machine
#  configures a brand new Ubuntu machine
sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-1.8 -y
sudo apt-get -y update
sudo apt-get -y install haproxy=1.8.\*
sudo echo -e "\nfrontend localnodes \n\tbind *:80 \n\tmode http \n\tdefault_backend nodes" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\nbackend nodes\n\tmode http\n\tbalance roundrobin\n\tserver 982-web-01 35.237.196.218:80 check\n\tserver 982-web-02 34.224.58.38:80 check\n" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
